---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
        exclude_types: ["markdown"]
        stages: [pre-commit]
      - id: trailing-whitespace
        exclude_types: ["markdown"]
        stages: [pre-commit]
      - id: mixed-line-ending
        stages: [pre-commit]
      - id: fix-byte-order-marker
        stages: [pre-commit]
      - id: check-executables-have-shebangs
        stages: [pre-commit]
      - id: check-merge-conflict
        stages: [pre-commit]
      - id: check-symlinks
        stages: [pre-commit]
  - repo: https://github.com/zricethezav/gitleaks.git
    rev: v8.22.1
    hooks:
      - id: gitleaks
        stages: [pre-commit]
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.352
    hooks:
      - id: checkov_container
        args:
          - --framework=dockerfile
          - --file=Dockerfile
        files: Dockerfile
