{{- if and .Values.caBundle (not .Values.caBundleExistingConfigMap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cainjekt.caBundleConfigMapName" . }}
  namespace: {{ include "cainjekt.namespace" . }}
  labels:
    {{- include "cainjekt.labels" . | nindent 4 }}
data:
  {{ .Values.caBundleKey }}: |
    {{- .Values.caBundle | nindent 4 }}
{{- end }}
