kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.nri.v1.nri"]
    disable = false
    socket_path = "/var/run/nri/nri.sock"
    plugin_registration_timeout = "5s"
    plugin_request_timeout = "2s"
nodes:
- role: control-plane
  image: kindest/node:v1.35.0
