apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- rbac.yaml
- configmap.yaml
- daemonset.yaml

commonLabels:
  app: cainjekt

images:
- name: cainjekt
  newName: ghcr.io/tsuzu/cainjekt
  newTag: latest
